### ISSUE TITLE
กด Claim Reward ในหน้า Assets ค่า Your total reward ไม่ลดลงต้องรีเฟสเองถึงจะเปลี่ยน

### ISSUE THREAD

**Issue by teekawut-piti** [jventures-jdn/project-staking-ui#3]
กด Claim Reward ในหน้า Assets ค่า Your total reward ไม่ลดลงต้องรีเฟสเองถึงจะเปลี่ยน
วิธีทดสอบ
1.ไปที่หน้า Assets
2.กด Claim Reward ในหน้า Assets ทำธุรกรรมให้เสร็จ
3.จะสังเกตได้ว่า ค่า Your total reward ไม่ยอมลดลง ต้องรีเฟสเองถึงจะเปลี่ยน

**Comment by vasin-peach** [comment]
ลองเทสใหม่นะคะ อันนี้พีชไม่เจอปัญหา
